[package]
version = "0.1.0"
name = "riscv-zkvm-script"
edition = "2021"
default-run = "riscv-zkvm"

[[bin]]
name = "riscv-zkvm"
path = "src/bin/main.rs"

[dependencies]
sp1-sdk = "5.0.0"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0.200", default-features = false, features = ["derive"] }
clap = { version = "4.0", features = ["derive", "env"] }
tracing = "0.1.40"
hex = "0.4.3"
alloy-sol-types = { workspace = true }
riscv-zkvm-lib = { path = "../lib" }
dotenv = "0.15.0"

[build-dependencies]
sp1-build = "5.0.0"
